// // const base_url = 
const baseUrl = 'http://192.169.243.70:4006/';

export const AppSettings = {
    contactData: baseUrl + 'sendemail',
    subscribe: baseUrl + 'addsubscribe'
}
// const baseUrl = 'http://192.169.243.70:3000/v1/';

// export const AppSettings = {
//     registrationUrl: baseUrl + 'users/registration',
//     loginUrl: baseUrl + 'users/login',
//     forgotPw: baseUrl + 'users/forgot_password',
//     changePwdUrl: baseUrl + 'users/change_password',
//     updateProfile: baseUrl + 'users/update_profile',
//     categoriesUrl: baseUrl + 'categories/grocery/cat',
//     subCatUrl: baseUrl + 'sub_categories',
//     productUrl: baseUrl + 'products',
//     addToCart: baseUrl + "vendor/cart_details",
//     delCart: baseUrl + 'vendor/cart_details/users',
//     getCart: baseUrl + 'vendor/cart_details/users',
//     loginDetailsUrl: baseUrl + 'users/',
//     getWholeSellersUrl: baseUrl + 'wholesalers',
//     getBanners: baseUrl + 'banners/user_grocery',
//     ProductById: baseUrl + "products/product_id",
//     wholesellerById: baseUrl + "wholesalers",
//     addaddress: baseUrl + "delivery_address/user",
//     getAddress: baseUrl + "delivery_address/user",
//     delAddress: baseUrl + "delivery_address",
//     setDelAdd: baseUrl + "delivery_address/user",
//     paymentType: baseUrl + "payment_options",
//     palceOrder: baseUrl + "place_order/user_orders",
//     getPlaceOrd: baseUrl + "place_order/user_orders/grocery_products",
//     orderSummary: baseUrl + "place_order/order_summary",
//     productByCatId: baseUrl + "vendor/products/categoryproducts",
//     productBySubCatId: baseUrl + "vendor/products/subcategoryproducts",
//     searchProducts: baseUrl + 'products/search',
//     wholeProducts: baseUrl + "/products/wholesaler_products",
//     ordById: baseUrl + "place_order/order_products",
//     reqProducts: baseUrl + "place_order/request_products/vendor",
//     updateProd: baseUrl + "place_order/pricing",
//     contactUsUrl: baseUrl + "contact_us",
//     getAddbyId: baseUrl + "delivery_address/address_id",
//     updateAddress: baseUrl + "delivery_address",
//     getAddedData: baseUrl + "vendor_products",
//     delProd: baseUrl + "vendor_products/product",
//     updateCart: baseUrl + "vendor/cart_details",
//     addWish: baseUrl + "wish_list",
//     getWish: baseUrl + "wish_list",
//     delWish: baseUrl + "wish_list",
//     getVouchers: baseUrl + "vouchers",
//     applyVoucher: baseUrl + "vouchers/applyvoucher",
//     getSlots: baseUrl + "delivery_slots/all_slots",
//     modifyCart: baseUrl + "vendor/cart_details",
//     getAllProducts: baseUrl + "vendor/products/getallapprovedproducts",
//     getBrands: baseUrl + "products/grocery_brands",
//     getVegetables: baseUrl + "products/vegetables",
//     getFruits: baseUrl + "products/fruits",
//     getTea: baseUrl + "products/tea",
//     getBread: baseUrl + "products/bread",
//     getJuice: baseUrl + "products/juice",
//     getBeaty: baseUrl + "products/users/beauty_products",
//     modifyWish: baseUrl + "wish_list",
//     changeForgot: baseUrl + "users/change_password",
//     otpUrl: baseUrl + "users/request_otp",
//     getFooter: baseUrl + "footer_table/getfooter/",
//     getVendors: baseUrl + "wholesalers/getvendorbasedonpincode",
//     getuserCats: baseUrl + "categories/getcategories/showinuser",
//     getVendorProds: baseUrl + "vendor/products/vedproductstoshowinuser",
//     updategetCart: baseUrl + "vendor/cart_details/updateuserorvenderid/session",
//     fiterCatProds: baseUrl + "vendor/products/filtercatproducts/cost",
//     fitersubCatProds: baseUrl + "products/filtersubcatproducts/cost",
//     fiterVenProds: baseUrl + "vendor/products/filtervedproductstoshowinuser/price",
//     filterCatHtoL: baseUrl + "vendor/products/filtercatproducts/hightolow",
//     filterSubCatHtoL: baseUrl + "vendor/products/filtersubcatproducts/hightolow",
//     filterVenHtoL: baseUrl + "vendor/products/filtervedproductstoshowinuser/hightolow",
//     filterCatLtoH: baseUrl + "vendor/products/filtercatproducts/lowtohigh",
//     filterSubCatLtoH: baseUrl + "vendor/products/filtersubcatproducts/lowtohigh",
//     filterVendorLtoH: baseUrl + "vendor/products/filtervedproductstoshowinuser/lowtohigh",
//     getAllCountries: baseUrl + "products/getcountrys/all",
//     sortByCountry: baseUrl + "vendor/products/filtercatproducts/country",
//     sortByCountrySubcat: baseUrl + "vendor/products/filtersubcatproducts/country",
//     sortByCountryVenId: baseUrl + "vendor/products/filtervedproductstoshowinuser/country",
//     sortBySizeCats: baseUrl + "vendor/products/filtercatproducts/size",
//     sortBySizeSubCats: baseUrl + "vendor/products/filtersubcatproducts/size",
//     sortBySizeVendor: baseUrl + "vendor/products/filtervedproductstoshowinuser/size",
//     getBannerProds: baseUrl + "banners/bannerproducts",
//     checkQuty: baseUrl + "vendor/cart_details/stockavailable"

// }